### ISSUE TITLE
Textbook RSA?

### ISSUE THREAD

**Issue by mmaker** [siyengar/private-fraud-prevention#1]
Hi
I'm glad that Facebook™ is working on anonymous credentials to protect the privacy of its users! 
Reading the source code I had a few concerns:

The token which is generated here:
https://github.com/siyengar/private-fraud-prevention/blob/024e76739e6af3e8219513b32608a80fcf8179c8/chrome/background.js#L136
https://github.com/siyengar/private-fraud-prevention/blob/024e76739e6af3e8219513b32608a80fcf8179c8/app.py#L219-L221

then blinded here:
https://github.com/siyengar/private-fraud-prevention/blob/0d55a0ed168df3fb808512003d139b093311eef4/crypto/crypto.py#L53-L60
and signed here: 
https://github.com/siyengar/private-fraud-prevention/blob/024e76739e6af3e8219513b32608a80fcf8179c8/crypto/crypto.py#L34-L39
does not prevent one-more unforgeability. 
Am I saying something terribly wrong here? The following attack would work, correct?
```python
In [1]: import crypto
In [8]: import os
In [9]: token = os.urandom(16)
In [10]: blind = os.urandom(16)
In [3]: sk = crypto.get_rsa_key(None)
In [5]: pk = crypto.get_public_key(None)
In [12]: blinded_message = crypto.blind_message(pk, token, blind)
In [19]: signature = crypto.sign_message(sk, blinded_message)
In [20]: signature = crypto.unblind_message(pk, signature, blind)
In [21]: crypto.validate_signature(pk, token, signature)
Out[21]: True
In [34]: signature2 = (int.from_bytes(signature, 'big')**2 % pk.n).to_bytes(512, 'big')
In [35]: token2 = (int.from_bytes(token, 'big')**2 % pk.n).to_bytes(32, 'big')
In [36]: crypto.validate_signature(pk, token2, signature2)
Out[36]: True
```

Even more importantly, is it correct to say that right now the client is asking for the entropy to the server, including token and blinding factor? Wouldn't this break unlinkability?

Hope this will be useful to you, cheers!

**Comment by siyengar** [comment]
@mmaker there were some limitations on what we could do with rsa blinding in a browser extension because of lack of support for bignums in js. So instead of actually doing the crypto in the browser, we do the rsa based crypto in a python service which we call the “browser” module including random number generation as well for convenience. In a real deployment, everything in the browser module would be implemented by the browser.

Also we would not deploy textbook rsa in production anywhere, this is just intended to be a demo project to demonstrate the flow with blind signatures. Ideally we’d use some scheme like rsapss or rsa fdh. The malleability of the token is not good because you’d be able to bypass the bot verification validation for subsequent requests. We’re aware of this, but will probably leave implementing pss for future work or when we get some time to hook it up in python.

Thanks for looking :) feel free to reopen in case of other comments

**Comment by siyengar** [comment]
Fixed using https://github.com/siyengar/private-fraud-prevention/commit/bf120004d5b6f6f979de263e71300032e71b4872. while it isn't full domain hashing, it will at least break the malleability :)
